# Generated by Django 2.1.1 on 2018-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendsInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='moneyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expensive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
    ]
